# Generated by Django 6.0.3 on 2026-04-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('is_online', models.BooleanField()),
                ('error_message', models.TextField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
