# Generated by Django 6.0.3 on 2026-04-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0005_alter_endpoint_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpointlog',
            old_name='monitor',
            new_name='endpoint',
        ),
    ]
