ARG PYTHON_VERSION=python3.14-alpine

FROM ghcr.io/astral-sh/uv:${PYTHON_VERSION}

 ENV PYTHONUNBUFFERED=1 \
     PYTHONDONTWRITEBYTECODE=1 \
     UV_COMPILE_BYTECODE=1 \
     UV_LINK_MODE=copy \
     XDG_CACHE_HOME=/app/.cache
     ENV PATH="/app/.venv/bin:$PATH"

WORKDIR /app

COPY pyproject.toml uv.lock* ./

RUN --mount=type=cache,target=/var/cache/apk \
     --mount=type=cache,target=/root/.cache/uv \
     --mount=type=cache,target=/root/.cache/pip \
     apk add --no-cache git netcat-openbsd bash curl nodejs && \
     uv sync --locked --no-install-project

COPY . .

EXPOSE 8000

CMD ["uv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
